sonar.projectKey=mfozmen_child-book-generator
sonar.organization=mfozmen

sonar.sources=src,build.py
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
